config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  get '/user' => "home#index", :as => :user_root

  root to: "home#index"
    #HOME
    get "/home", to: "home#index"
    resources :home, only: :index

    #ABOUT
    get "/about", to: "about#index"
    resources :about, only: :index

    #CONTACT
    get "/contact", to: "contact#index"
    resources :contact, only: :index

    #SIGNUP
    get "/sign_up", to: "sign_up#index"
    resources :sign_up, only: :index

    #LOGIN
    get "/login", to: "login#index"
    resources :login, only: :index

    #USER MAIN
    get "/user_main", to: "user_main#index"
    resources :user_main, only: :index

    #COLLEGES
    resources :colleges, only: %i[new create index show] do
      resources :courses, only: %i[new create]
    end

    #COURSES
    resources :courses, only: %i[new create index show] do 
      resources :reviews, only: %i[new create] 
    end

    #TRENDING COURSES
    get "/trending_courses", to: "trending_courses#index"
    resources :trending_courses, only: :index

    #REVIEWS
    resources :reviews, only: %i[new create] 
      #:edit, :update, :destroy]

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/college.rb
class College < ApplicationRecord
  has_many :courses
  #belongs_to :user
  end 

app/models/course.rb
class Course < ApplicationRecord
    has_many :reviews
    belongs_to :college

    def average_rating 
        
        reviews.average(:rating)&.round(2) || 0
    end
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :course
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews
  #has_many :colleges
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    if params[:query] 
      @courses = Course.where("name like ?", "%#{params[:query].downcase}%")
    else
      @courses = Course.all
    end
  end

  def show
    @course = Course.find(params[:id])
  end

  def create
    @college = College.find(params[:college_id])
    @course = @college.courses.new(create_params)

    @course.college_id = @college.id

    if @course.save
      redirect_to @course
    else
      render "new"
    end
  end

  private 
  def create_params
    params.permit(:course_id, :name)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  #before_action :authenticate_user!
  def index
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
  end
  
  def new
    @course = Course.find(params[:course_id])
  end

  def create
    @course = Course.find(params[:course_id])
    @review = @course.reviews.new(create_params)

    @review.user_id = current_user.id

    if @review.save
      redirect_to @course
    else
      render "new"
    end
  end

  private 
  def create_params
    params.permit(:semester, :summary, :year, :rating, :course_id, :user_id)
  end



end

app/controllers/sign_up_controller.rb
class SignUpController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/sign_up_helper.rb
module SignUpHelper
end

app/helpers/user_main_helper.rb
module UserMainHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>eduScore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>

  <!--Flash messages-->
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

</html>

app/views/shared/_footer.html.erb
<!---footer-->
<footer class = "page-footer">
  <p>&copy; <span id = "date">2021</span>
    <span class = "footer-logo">
      eduScore
    </span>
    Built by AC
  </p>
</footer>
<!---end of footer-->

app/views/shared/_main_end.html.erb
</main>

app/views/shared/_main_start.html.erb
<main class="page"/>

app/views/shared/_navbar_setup.html.erb
<!DOCTYPE html>
<html>
<!Anything included in the head element will not be displayed to the user
The header is where meta-information about our pages is placed,
and also where stuff required for pages to render correctly is placed.
-->
<head>
  <!--TITLE IDEAS:
    -foreCourse
    -EduPath
    -CourseGuide
    -CourseGenie
    -CoursePath
    -EduCourses
    -EduRate
    -RateDotEdu
    -forewordCourse
    -PathMyCourse
    -DisCourse
    -CourseWay
    -CourseTrack
    -EduGrade
    -EduScore
    -EduGuide
    -CourseGrade
    -eduRank
-->
  <title>
    Home
  </title>
  <meta charset="utf-8"/>
  <!--NORMALIZE--->
  <%link_to "./css/normalize.css", stylesheet_link_tag %>

  <!---FAVICON-->
  <!--link_to "./assets/favicon.ico", favicon_link_tag, style:"image/x-icon"-->
  <link rel="shortcut icon" href="./assets/favicon.ico" type="image/x-icon" />

  <!--FONT AWESOME ICON-->
  <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css"
    />
  <!--APPLICATION CSS-->
  <!--link rel="stylesheet" href="./css/main.css"-->
  <%link_to "./css/application.css.erb", stylesheet_link_tag %>
</head>

<body>
<!--NAVIGATION BAR-->
<nav class="navbar">
  <div class="nav-center">
    <!--header-->
    <div class = "nav-header">
      <%=link_to( image_tag("logo.png", :alt => "eduScore"), home_path, :class=>"nav-logo") %>
      <button type="button" class="btn nav-btn">
        <i class="fas fa-align-justify"></i>
      </button>
    </div>
    <!--links-->
    <div class="btn nav-links">
      <!--<link_to "home", home_index_path, :class=>"nav-link">
      #<link_to "about", about_index_path, :class=>"nav-link">
      #<!link_to login_path, :class=>"nav-link"> Sign Up/Login-->
      <!--<div class="btn navbarb">-->
        <a href="<%= home_path %>", class="nav-link">home</a>
        <a href="<%= about_index_path %>", class="nav-link">about</a>
        <a href="<%= colleges_path %>", class="nav-link">search</a>
        <a href="<%= new_user_registration_path %>", class="nav-link">sign up/login</a>
      <!--/div>-->
    </div>
    <div class="nav-link contact-link">
      <a href="<%=contact_path%>", class="btn">contact</a>
    </div>
  </div>
</nav>
<!--end of nav-->

app/views/shared/_userin_main_nav.html.erb
<!DOCTYPE html>
<html>
<!Anything included in the head element will not be displayed to the user
The header is where meta-information about our pages is placed,
and also where stuff required for pages to render correctly is placed.
-->
<head>
  <!--TITLE IDEAS:
    -foreCourse
    -EduPath
    -CourseGuide
    -CourseGenie
    -CoursePath
    -EduCourses
    -EduRate
    -RateDotEdu
    -forewordCourse
    -PathMyCourse
    -DisCourse
    -CourseWay
    -CourseTrack
    -EduGrade
    -EduScore
    -EduGuide
    -CourseGrade
    -eduRank
-->
  <title>
    Home
  </title>
  <meta charset="utf-8"/>
  <!--NORMALIZE--->
  <%link_to "./css/normalize.css", stylesheet_link_tag %>

  <!---FAVICON-->
  <!--link_to "./assets/favicon.ico", favicon_link_tag, style:"image/x-icon"-->
  <link rel="shortcut icon" href="./assets/favicon.ico" type="image/x-icon" />

  <!--FONT AWESOME ICON-->
  <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css"
    />
  <!--APPLICATION CSS-->
  <!--link rel="stylesheet" href="./css/main.css"-->
  <%link_to "./css/application.css.erb", stylesheet_link_tag %>
</head>

<body>
<!--NAVIGATION BAR-->
<nav class="navbar">
  <div class="nav-center">
    <!--header-->
    <div class = "nav-header">
      <%=link_to( image_tag("logo.png", :alt => "foreCourse"), home_index_path, :class=>"nav-logo") %>
      <button type="button" class="btn nav-btn">
        <i class="fas fa-align-justify"></i>
      </button>
    </div>
    <!--links-->
    <div class="btn nav-links">
      <!--<link_to "home", home_index_path, :class=>"nav-link">
      #<link_to "about", about_index_path, :class=>"nav-link">
      #<!link_to login_path, :class=>"nav-link"> Sign Up/Login-->
      <!--<div class="btn navbarb">-->
      <a href="<%= home_index_path %>", class="nav-link">home</a>
      <a href="<%= about_path %>", class="nav-link">about</a>
      <a href="<%= colleges_path %>", class="nav-link">Search for An Institution</a>

      <!--< @user.colleges.each do | college | >
      < link_to Find a Course, college_path(college), class:"nav-link">-->
      <a href="<%= courses_path %>", class="nav-link">review a course</a>
      <!--<a href="<%= courses_path %>", class="nav-link">find a course</a>-->
    </div>

    <div class="nav-link logout-link">
      <%=link_to "log out", destroy_user_session_path, method: :delete, class:"btn"%>
    </div>

  </div>
</nav>
<!--end of nav-->