config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  get '/user' => "home#index", :as => :user_root

  root to: "home#index"
    #HOME
    get "/home", to: "home#index"
    resources :home, only: :index

    #ABOUT
    get "/about", to: "about#index"
    resources :about, only: :index

    #CONTACT
    get "/contact", to: "contact#index"
    resources :contact, only: :index

    #SIGNUP
    get "/sign_up", to: "sign_up#index"
    resources :sign_up, only: :index

    #LOGIN
    get "/login", to: "login#index"
    resources :login, only: :index

    #USER MAIN
    get "/user_main", to: "user_main#index"
    resources :user_main, only: :index

    #COLLEGES
    resources :colleges, only: %i[new create index show] do
      resources :courses, only: %i[new create]
    end

    #COURSES
    resources :courses, only: %i[new create index show] do 
      resources :reviews, only: %i[new create] 
    end

    #TRENDING COURSES
    get "/trending_courses", to: "trending_courses#index"
    resources :trending_courses, only: :index

    #REVIEWS
    resources :reviews, only: %i[new create] 
      #:edit, :update, :destroy]

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/college.rb
class College < ApplicationRecord
  has_many :courses
  #belongs_to :user
  end 

app/models/course.rb
class Course < ApplicationRecord
    has_many :reviews
    belongs_to :college

    def average_rating 
        
        reviews.average(:rating)&.round(2) || 0
    end
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :course
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews
  #has_many :colleges
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    stored_location_for(resource) || home_path
  end
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
  #def index 
    #@college = College.find(params[:id])
  #end

  #def add_reference College 
    #@College.user_id = current_user.id
  #end

  def new
    @college = College.new
  end

  def create
    @college = College.new(create_params)

    if @college.save
      redirect_to @college
    else
      render "new"
    end
  end
  
  def index
      if params[:query] 
        @colleges = College.where("name like ?", "%#{params[:query].downcase}%")
      else
        @colleges = College.all
      end
  end

  def show
    @college = College.find(params[:id])
    #@reviews = @course.reviews
  end

  private 
  def create_params
    params.permit(:name, :state, :city)
  end

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    if params[:query] 
      @courses = Course.where("name like ?", "%#{params[:query].downcase}%")
    else
      @courses = Course.all
    end
  end

  def show
    @course = Course.find(params[:id])
  end

  def create
    @college = College.find(params[:college_id])
    @course = @college.courses.new(create_params)

    @course.college_id = @college.id

    if @course.save
      redirect_to @course
    else
      render "new"
    end
  end

  private 
  def create_params
    params.permit(:course_id, :name)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  #before_action :authenticate_user!
  def index
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
  end
  
  def new
    @course = Course.find(params[:course_id])
  end

  def create
    @course = Course.find(params[:course_id])
    @review = @course.reviews.new(create_params)

    @review.user_id = current_user.id

    if @review.save
      redirect_to @course
    else
      render "new"
    end
  end

  private 
  def create_params
    params.permit(:semester, :summary, :year, :rating, :course_id, :user_id)
  end



end

app/controllers/sign_up_controller.rb
class SignUpController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/sign_up_helper.rb
module SignUpHelper
end

app/helpers/user_main_helper.rb
module UserMainHelper
end

app/views/colleges/index.html.erb
<!--TITLE NAVBAR HEADER-->
<% if user_signed_in? %>
  <%=render partial:"shared/userin_main_nav"%>
<%else %>
  <%=render partial: "shared/navbar_setup"%>
<%end%>

<%=render partial: "shared/main_start" %>

<section class = "find_school-page">
    <%= form_with url: colleges_path, class:"form searchft", method: :get do |form| %>
      <%= form.text_field :query, placeholder:"Search", class: "form-input search_area"%>
      <%= form.submit "Search", class:"btn btn-block search_btn"%>
    <% end %> 

    <% if @colleges.any? %>
      <div class="basic_container fit_school_table_container">
        <table class="school_table">
          <tr class="school_table_header">
            <th>Name</th>
            <th>City</th>
            <th>State</th>
          </tr>
          <% @colleges.each do | college | %>
            <tr class= "school_table_data">
              <td>
                <%= link_to college.name, college_path(college)%>
              </td>
              <td>
              <%= college.city %>
              </td>
              <td>
              <%= college.state %>
              </td>
            </tr>
          <% end %>
        </table>
      </div>
    <% else %>
      <h2> No colleges found! </h2>
      <% if user_signed_in? %>
        <%= link_to "Add a College", new_college_path, class:"btn btn-block add-college_btn"%>
      <%end%>
    <% end %>

</section>

<%=render partial: "shared/main_end" %>
<%=render partial: "shared/footer" %>

app/views/colleges/new.html.erb
<!--NAVBAR HEADER-->
<% if user_signed_in? %>
  <%=render partial:"shared/userin_main_nav"%>
<%else %>
  <%=render partial: "shared/navbar_setup"%>
<%end%>
<%=render partial: "shared/main_end" %>

<section class = "college_new-page">
  <article>
    <h2 class="college_new_page_h2">
      Add a College
    </h2>
    <div class="basic_container review_container">
      <%= form_with url: colleges_path do |form| %>
        <div class="course_name_code">
          <%= form.label :name, "Name", class:"form-label college_form"%>
          <%= form.text_field :name, class:"form-input college_add_form_input"%>

          <%= form.label :state, "State", class:"form-label course_year"%>
          <%= form.text_field :state, class:"form-input college_add_form_input"%>

          <%= form.label :city, "City", class:"form-label course_year"%>
          <%= form.text_field :city, class:"form-input college_add_form_input"%>
        </div>
      <%= form.submit "Submit", class:"btn btn-block review_submit_btn"%>
      <%end%>
    </div>
  </article>
</section>

<%=render partial: "shared/main_end" %>
<%=render partial: "shared/footer" %>

app/views/colleges/search.html.erb
<!--TITLE NAVBAR HEADER-->
<% if user_signed_in? %>
  <%=render partial:"shared/userin_main_nav"%>
<%else %>
  <%=render partial: "shared/navbar_setup"%>
<%end%>

<%=render partial: "shared/main_start" %>

<section class = "find_school-page">
  <%= form_with url: colleges_path, class:"form searchft", method: :get do |form| %>
    <%= form.text_field :query, placeholder:"Search", class: "form-input search_area"%>
    <%= form.submit "Search", class:"btn btn-block search_btn"%>
  <% end %>

    <div class="basic_container school_table_container">
      <table class="school_table">
        <tr class="school_table_header">
          <th>Name</th>
          <th>City</th>
          <th>State</th>
        </tr>
        <% @colleges.each do | college | %>
        <tr class= "school_table_data">
          <td>
            <%= link_to college.name, college_path(college)%>
          </td>
          <td>
          <%= college.city %>
          </td>
          <td>
          <%= college.state %>
          </td>
        </tr>
        <% end %>
      </table>
    </div>
</section>

<%=render partial: "shared/main_end" %>
<%=render partial: "shared/footer" %>

app/views/colleges/show.html.erb
<!--TITLE NAVBAR HEADER-->
<% if user_signed_in? %>
  <%=render partial:"shared/userin_main_nav"%>
<%else %>
  <%=render partial: "shared/navbar_setup"%>
<%end%>

<!--MAIN-->
<%=render partial: "shared/main_start" %>
<section class = "colleges-page">
    <div class="colleges-page_header">
      <h2>
      <%= @college.name %>
      </h2>

      <%if user_signed_in? %>
        <%= link_to "Add a Course", new_college_course_path(@college), class:"btn btn-block add-course_btn" %>
      <%end%>
      
    </div>   
    <div class = "basic_container courses_in_colleges_container" >
      <h4>
        Courses | <%=@college.name%>
      </h4>
      <table class = courses_at_college_table>
        <tr class="college_courses_header">
            <th>Overall Rating</th>
            <th>Course Name</th>
            <th>Course Number</th>
            <th>Number of Reviews</th>
        </tr>
        
        <% @college.courses.sort_by { |c| c.average_rating }.reverse.each do | course | %>
          <tr class="course_at_college">
            <td>
            <%if course.reviews.any?%>
              <%=course.average_rating%>
            <%else%> 
              No reviews
            <%end%>
            </td>
            <td>
              <%= link_to course.name, course_path(course)%>
            </td>
            <td>
            <%= link_to course.course_id, course_path(course) %>
            </td>
            <td>
            <%=course.reviews.count%>
            </td>
          </tr>
        <%end%>
      </table>
    </div>
</section>

<!--FOOTER-->
<%=render partial: "shared/main_end" %>
<%=render partial: "shared/footer" %>

app/views/contact/index.html.erb
<!--TITLE NAVBAR HEADER-->
<% if user_signed_in? %>
  <%=render partial:"shared/userin_main_nav"%>
<%else %>
  <%=render partial: "shared/navbar_setup"%>
<%end%>

<%=render partial: "shared/main_start" %>
<section class = "contact-page">
  <article class="contact">
    <div class="basic_container contact_container">
      <h4>
        Contact Us
      </h4>
      <p>
        Email: contact.eduscore@gmail.com
      </p>
    </div>
  </article>
</section>
<%=render partial: "shared/main_end" %>
<%=render partial: "shared/footer" %>

app/views/courses/index.html.erb
<!---list all courses--->
<!--TITLE NAVBAR HEADER-->
<% if user_signed_in? %>
  <%=render partial:"shared/userin_main_nav"%>
<%else %>
  <%=render partial: "shared/navbar_setup"%>
<%end%>

<%=render partial: "shared/main_start" %>


<!--<%= form_with url: colleges_path, class: "select_college", method: :get do |form| %>
  <div class="basic_container select_college_container">
    <div class="course_name_code">
      <%= form.label :name, "Select College to Search From", class:"form-label course_year"%>
      <%= form.select :name, College.all.collect {|p| [ p.name, p.id ] },  class: "form-input college_names_inputs"%>
    </div>
  </div>
<%end%>-->

<section class = "find_course-page">
  <%= form_with url: courses_path(@college), class:"form searchft", method: :get do |form| %>
    <%= form.label "Search for a course to review: ", class:"form-label course_search_prompt"%>
    <%= form.text_field :query, placeholder:"Search", class: "form-input search_area"%>
    <%= form.submit "Search", class:"btn btn-block search_btn"%>
  <% end %>

  <% if @courses.any? %>
    <div class="basic_container courses_table_container">
      <h4>
          Courses Available for Review
      </h4>
      <table class="courses_table">
        <tr class="courses_table_header">
          <th>Course Name</th>
          <th>Course Number</th>
          <th>College</th>
        </tr>
        <% @courses.each do | course | %>
          <tr class="courses_table_data">
            <td>
              <%= link_to course.name, course_path(course)%>
            </td>
            <td>
            <%= link_to course.course_id, course_path(course)  %>
            </td>
            <td>
            <%= link_to course.college.name, college_path(course.college) %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  <%else%>
    <h2> No courses found! </h2>
    <% if user_signed_in? %>
      <%= link_to "Add a Course to a College",  new_college_course_path(College.first), class:"btn btn-block add-course_to_college_btn", add_course: true %>
      <!---<%add_course = true%>--->
    <%end%>
  <%end%>
    
</section>

<%=render partial: "shared/main_end" %>
<%=render partial: "shared/footer" %>

app/views/courses/new.html.erb
<!--NAVBAR HEADER-->
<% if user_signed_in? %>
  <%=render partial:"shared/userin_main_nav"%>
<%else %>
  <%=render partial: "shared/navbar_setup"%>
<%end%>
<%=render partial: "shared/main_end" %>

<section class = "course_new-page">
  <article>
    <h2 class="course_new_page_h2">
      Add a Course
    </h2>
    <div class="basic_container review_container">
      <%= form_with url: college_courses_path do |form| %>
        <div class="course_name_code">
          <%= form.label :course_id, "Course Number", class:"form-label college_form"%>
          <%= form.text_field :course_id, class:"form-input course_add_form_input"%>

          <%= form.label :name, "Course Name", class:"form-label course_year"%>
          <%= form.text_field :name, class:"form-input course_add_form_input"%>
        </div>
      <%= form.submit "Submit", class:"btn btn-block review_submit_btn"%>
      <%end%>
    </div>
  </article>
</section>

<%=render partial: "shared/main_end" %>
<%=render partial: "shared/footer" %>

app/views/courses/show.html.erb
<!---TITLE NAVBAR HEADER-->
<% if user_signed_in? %>
  <%=render partial:"shared/userin_main_nav"%>
<%else %>
  <%=render partial: "shared/navbar_setup"%>
<%end%>

<!--MAIN-->
<%=render partial: "shared/main_start" %>
<section class = "course_show-page">
  <h2>
    <%= @course.name %> |  <%= link_to  @course.college.name, college_path(@course.college), class: "college_name_a" %>
  </h2>

  <div class = "basic_container reviews_in_course_container" >
    <div class = "course_reviews_header">
      <h4>
        Reviews | <%=@course.name%>
      </h4>

      <% if user_signed_in? %>
        <%=link_to "Add Review", new_course_review_path(@course), class:"btn btn-block add-review_btn" %>
      <%end%>

    </div>


    <% @course.reviews.each do | review | %>
    <div class="basic_container reviews_container">
      <div class= "reviews_container_header">
        <div class = "review_rating_icon">

          <i class="fas fa-star">
          </i>
          <%= review.rating%>
      
        </div>
        <div class = "review_course_info">
          <%= review.semester %>
          <%= review.year %>
        </div>
      </div>

      <div class="review_summary_display">
        <%= review.summary%>
      </div>

      <div class = "reviewer_info">
        <%= review.user.email%>
      </div>
    </div>
    <%end%>

  </div>

</section>

<!--FOOTER-->
<%=render partial: "shared/main_end" %>
<%=render partial: "shared/footer" %>

app/views/home/index.html.erb
<!--TITLE NAVBAR HEADER-->
<% if user_signed_in? %>
  <%=render partial:"shared/userin_main_nav"%>
<%else %>
  <%=render partial: "shared/navbar_setup"%>
<%end%>

  <!--HEADER-->
<main class="page">
  <header class ="hero">
    <div class="hero-container">
      <div class="hero-text">
        <h1>See what your classmates are saying about their classes!</h1>
        <%= link_to "Find Your School", colleges_path, class: "btn"%>
      </div>
    </div>
  </header>
</main>

<!--FOOTER-->
<%=render partial: "shared/footer"%>
    <script src="./manifest.js"></script>
  </body>
</html>

app/views/sign_up/index.html.erb
<%=render partial: "shared/navbar_setup" %>
<%=render partial: "shared/main_start" %>
<section class = "sign_up">

  <form class ="form sign_up-form">
    <!--PROMPT USER FOR EMAIL-->
    <div class = "form_row">
      <h3>
        sign up
      </h3>
      <label for = "email" class = "form-label"> email </label>
      <input type="text" name="email"  id="email" class="form-input"/>
    </div>
    <!--PROMPT USER FOR PASSWORD-->
    <div class = "form_row">
      <hr width="100%" color="FFFFFFFF">
      <label for = "password" class = "form-label"> password </label>
      <input type="text" name="password"  id="password" class="form-input"/>
    </div>
    <!--CONFIRM PASSWORD-->
    <div class = "form_row">
      <hr width="100%" color="FFFFFFFF">
      <label for = "confirm_password" class = "form-label"> confirm password </label>
      <input type="text" name="confirm_password"  id="confirm_password" class="form-input"/>
    </div>
    <hr size="8" width="100%" color="FFFFFFFF">
    <button type="submit" class="btn btn-block">
      sign up
    </button>
  </form>
</section>
<%=render partial: "shared/main_end" %>
<%=render partial: "shared/footer" %>